server:
  port: 8081

  spring:
    datasourse:
      driver-class-name: org.postgresql.Driver
      url: jdbc:posgresql://localhost:5432/simple-app
      username: postgres
      password: postgrespass

    jpa:
      show-sql: true
      properties:
        hibernate:
          format-sql: true
